name: {{cookiecutter.project_name}} app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    {% raw -%}
    - uses: actions/checkout@v2
    - name: Set up Python ${{{{ matrix.python-version }}}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{{{ matrix.python-version }}}}
    {%- endraw %}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false --local && poetry install --no-root

    - name: Lint pre-commit
      run: |
        pre-commit run -a

    - name: Build Docker image
      run: |
        {% raw -%}
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
        {%- endraw %}
        docker build -f staging.dockerfile -t egnod/{{cookiecutter.project_name}}:latest .

    - name: Push Docker image
      run: |
        docker push egnod/{{cookiecutter.project_name}}:latest
